### ISSUE TITLE
Sneak peak

### ISSUE THREAD

**Issue by jcopps** [BennyThadikaran/RRG-Lite#1]
As I could see you are working on something really interesting. Could I get to have a look into it.

**Comment by BennyThadikaran** [comment]
The project is almost fully ready. I am still running tests to ensure its stable and reliable.

The configuration is very similar to Stock-patterns since I reused the loader class. If you're using EOD2, you already have everything you need to get started.

Follow the install and setup section in the README. 

Download my sectors.csv from this link - https://res.cloudinary.com/doyu4uovr/raw/upload/v1730526283/RRG-Lite/sectors_vwqau3.csv

`py init.py -f path/to/sectors.csv -b 'nifty 50'` 

See more detailed setup wiki: https://github.com/BennyThadikaran/RRG-Lite/wiki/Setup

Let me know if you need help setting up and do give me your feedback. 

More detailed usage instructions will follow in a few days.
